// <auto-generated />
using Autenticacao.API.Domain.Entities;
using Autenticacao.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Autenticacao.API.Infrastructure.Data.Migrations.AutenticacaoDb
{
    [DbContext(typeof(AutenticacaoDbContext))]
    [Migration("20180727193954_AutenticacaoInicialMigration")]
    partial class AutenticacaoInicialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Autenticacao.API.Domain.Entities.Conta", b =>
                {
                    b.Property<int>("ContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CONTA_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ContaUID")
                        .HasColumnName("UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("LOGIN");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("SENHA");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnName("SOBRENOME");

                    b.Property<int>("TipoConta")
                        .HasColumnName("TIPO");

                    b.HasKey("ContaId");

                    b.HasIndex("ContaUID");

                    b.ToTable("Conta");
                });
#pragma warning restore 612, 618
        }
    }
}
